version: '3'
services:
  app:
    build:
      context: .
    environment:
      # MYSQL_USER: ${MYSQL_USER}
      # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/muscle_platform
      - public-data:/muscle_platform/public
      - tmp-data:/muscle_platform/tmp
      - log-data:/muscle_platform/log
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      # MYSQL_USER: ${MYSQL_USER}
      # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/muscle_platform/public
      - tmp-data:/muscle_platform/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
