version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.0-node-browsers
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          DATABASE_HOST: 127.0.0.1
          RAILS_ENV: test

      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          MYSQL_DATABASE: circleci

    steps:
      - checkout
      - run: bundle install
      - run: rails db:create
      - run: rails db:migrate
      - run:
          name: rspec
          command: bin/rspec

workflows:
  ci:
    jobs:
      - build
