version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.0
              
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          DATABASE_HOST: 127.0.0.1
          DATABASE_USER: "root"
          DATABASE_PASSWORD: ""
          RAILS_ENV: test

      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: circleci

    steps:
      - checkout
      - run: bundle install
      - run: rails db:create
      - run: rails db:migrate
      - run:
          name: minitest
          command: rails test

workflows:
  sample: 
    jobs:
      - build
